#!/usr/bin/env bash
# Setup file for windows subsystem for linux
# By yoieh, 2017-02-07

# Update and upgrade system
sudo apt update
sudo apt upgrade

# Turn of terminal bell
INPUTRC_CONF=~/.inputrc
echo "# This file is generated by setup.git by yoieh" >> ${INPUTRC_CONF}
echo "# $(date)" > ${INPUTRC_CONF}
echo "# Turn of terminal bell" > ${INPUTRC_CONF}
echo "set bell-style none" > ${INPUTRC_CONF}

# Install git, this will allready be installed..
sudo apt install git

# Vim setup
git clone https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh

# Turn of bell in vim
VIM_CONF=~/.vim_runtime/my_configs.vim
echo "# This file is generated by setup.git file by yoieh" >> ${VIM_CONF}
echo "# $(date)" > ${VIM_CONF}
echo "# Turn of bell sound " > ${VIM_CONF}
echo "set visualbell" > ${VIM_CONF}

echo "# Open NERDTree automatically" > ${VIM_CONF}
echo "autocmd StdinReadPre * let s:std_in=1" > ${VIM_CONF}
echo "autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif"

# Install Vim plugins
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

# Install NodeJs
sudo apt install nodejs

# Install bower
sudo npm install bower -g

# Install php
sudo apt install php

# Install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"


exit 0
